# Generated by Django 5.1.5 on 2025-01-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(default='no type', max_length=50),
        ),
    ]
