# Generated by Django 5.1.5 on 2025-01-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0002_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], default='income', max_length=50),
        ),
    ]
